export const COUNTRY_OPTIONS = [
  "Agartha",
  "Afganistan",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyan",
  "Bahamas",
  "Banglades",
  "Barbados",
  "Barein",
  "Belgica",
  "Belice",
  "Benin",
  "Bielorrusia",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Butan",
  "Cabo Verde",
  "Camboya",
  "Camerun",
  "Canada",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Arabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "Espana",
  "Estados Unidos",
  "Estonia",
  "Etiopia",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea Ecuatorial",
  "Guinea-Bisau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungria",
  "India",
  "Indonesia",
  "Irak",
  "Iran",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomon",
  "Israel",
  "Italia",
  "Jamaica",
  "Japon",
  "Jordania",
  "Kazajistan",
  "Kenia",
  "Kirguistan",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Libano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macedonia del Norte",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Mali",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "Mexico",
  "Micronesia",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Oman",
  "Paises Bajos",
  "Pakistan",
  "Palaos",
  "Palestina",
  "Panama",
  "Papua Nueva Guinea",
  "Paraguay",
  "Peru",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "Republica Centroafricana",
  "Republica Checa",
  "Republica Democratica del Congo",
  "Republica Dominicana",
  "Republica del Congo",
  "Ruanda",
  "Rumania",
  "Rusia",
  "Samoa",
  "San Cristobal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucia",
  "Santo Tome y Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Suazilandia",
  "Sudafrica",
  "Sudan",
  "Sudan del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistan",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Tunez",
  "Turkmenistan",
  "Turquia",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
];
